# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Weekly Team Sync
on:
  push:
    branches: [ master ]
    
permissions:
  contents: read
  issues: write 
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        with:
          assignees: "monalisa, doctocat, hubot"
          labels: "weekly sync, docs-team"
          title: "Team sync"      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
