# This is a basic workflow to help you get started with Actions

name: Demo to create a PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  updateAuthor: 
    runs-on: ubuntu-latest
    steps:
      - name: checking out the code
        uses: actions/checkout@v2
        
      - name: Extract git commit data
        uses: testrepo/git-commit-action-data@v1.x
        
      - name: Raise PR
        uses: Kishore/create-pull-request@v3
        with: 
          branch: "auto-pr-branch"
          base: master
          title: demo
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }}
          body:
            This is test Github action to test
          token: ${{ secrets.GITHUB_TOKEN }}
          
      
    
